version: '3.3'

services:
    nginx:
        image: nginx
    db:
        image: mysql:5.7
        container_name: mysql_irondb
        ports:
            - "3306:3306"
        expose:
            - "3306"
        environment:
            - MYSQL_HOST=localhost
            - MYSQL_ROOT_PASSWORD=srujan123
            - MYSQL_USER=srujan
            - MYSQL_PASSWORD=srujan
            - MYSQL_DATABASE=irondb
        volumes:
            - "./db:/var/lib/mysql"
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: avengers
        ports:
            - "8000:5000"
        restart: always
        links:
            - db
        depends_on:
            - db
        command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"

